version: "3.9"
services:
  backend:
    build:
      context: ../../apps/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - ../../.env
    volumes:
      - ../../apps/backend:/app
  web:
    build:
      context: ../../apps/web
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - PUBLIC_API_BASE_URL=http://localhost:8000
    volumes:
      - ../../apps/web:/app
    depends_on:
      - backend
